//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supa_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int GoodID { get; set; }
        public int MarketID { get; set; }
        public string Location { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Remaining { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Market Market { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
