//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supa_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int MarketID { get; set; }
        public string MarketName { get; set; }
        public string MarketAdd { get; set; }
        public Nullable<int> MarketEst { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
