//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supa_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types3
    {
        public Types3()
        {
            this.Goods = new HashSet<Good>();
        }
    
        public string Class3 { get; set; }
        public string Class2 { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
        public virtual Types2 Types2 { get; set; }
    }
}
