//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supa_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types1
    {
        public Types1()
        {
            this.Types2 = new HashSet<Types2>();
        }
    
        public string Class1 { get; set; }
    
        public virtual ICollection<Types2> Types2 { get; set; }
    }
}
